### ISSUE TITLE
マークダウンテキストをペーストできるようにする

### ISSUE THREAD

**Issue by shimonosatoru** [uma-co82/LGTM#3]
githubとbitbucketに対応させる

**Comment by uma-co82** [comment]
おkです👻

**Comment by shimonosatoru** [comment]
@uma-co82 あ、まだBitbucketの対応が終わってないので終わったらcloseさせます！

**Comment by uma-co82** [comment]
🙇‍♂️

**Comment by shimonosatoru** [comment]
まさかのappendすると消されるという仕様w
これはBitbucket対応は無理かもしれない、、、

**Comment by uma-co82** [comment]
なぬ、、、
ちょっと試して見ますww

**Comment by uma-co82** [comment]
<img width="375" alt="スクリーンショット 2019-04-04 10 38 18" src="https://user-images.githubusercontent.com/42496916/55523864-e9a59600-56c5-11e9-82cc-516dd7fa33e8.png">

ここのpタグに入力した物が入るみたいですが今実装はこのpタグに直接入れる感じですか？🤔

**Comment by shimonosatoru** [comment]
@uma-co82 
### 残りのやること
- [x] 不特定多数のサイトで使えるようにする（https://, http://）
- [x] クリップボードにコピーした旨を2秒くらいお知らせする

**Comment by uma-co82** [comment]
@shimonosatoru 
両方完了です🤗

**Comment by shimonosatoru** [comment]
マージしたらcloseしちゃってください〜
