### ISSUE TITLE
contentsで""を外すやり方でもっといいのがあるはず

### ISSUE THREAD

**Issue by shimonosatoru** [uma-co82/LGTM#4]
popupから送られてきたデータは`""`がくっついていてそれを下記のようなコードで消してるので何かいい方法がないかと模索中
```
var contents = message.slice(1).slice(0, -1);
```

**Comment by uma-co82** [comment]
間違いだったらすいません😭
これjsonで飛んで来てるのを受け取って成形してる感じですか？？

**Comment by uma-co82** [comment]
jsonでkey(message)があるんであれば

```
var contents = tabs.message
```
とかじゃ難しいかな、、
これなら受け取り方とか直さなきゃかも？？🤔

**Comment by shimonosatoru** [comment]
>これjsonで飛んで来てるのを受け取って成形してる感じですか？？

ぼくもjsonかなと思ったんですが`""`だけだったので一番手っ取り早い方法を選びました。
`{}`はなかったんですよね〜

> ```
> var contents = tabs.message
> ```
> とかじゃ難しいかな、、
> これなら受け取り方とか直さなきゃかも？？🤔

これちょっと試してみます！
